### ISSUE TITLE
Example Dataset is not available

### ISSUE THREAD

**Issue by grunblatt-git** [invoke-ai/invoke-training#102]
When following the [quickstart tutorial](https://invoke-ai.github.io/invoke-training/get-started/quick-start-gui/), the dataset `lambdalabs/pokemon-blip-captions` is used in the default config.

Apparently the dataset was taken offline, so there is currently no dataset for the quickstart available. (see https://huggingface.co/datasets/lambdalabs/pokemon-blip-captions)

> Notice of DMCA Takedown Action
We have received a DMCA takedown notice from The Pokémon Company International, Inc.
> In response to this action, we have taken down the dataset.
> We appreciate your understanding.

**Comment by grunblatt-git** [comment]
So I tried to get the training tool running with the 4 images of "bruce the gnome" that are included in the `sample_data` folder.

I created a dataset `test-dataset.jsonl` in the UI:
```
{"image": "/content/invoke-training/sample_data/bruce_the_gnome/003.png", "text": "bruce_the_gnome in a kitchen corner,  from above"}
{"image": "/content/invoke-training/sample_data/bruce_the_gnome/004.png", "text": "bruce_the_gnome in front of a wall frontal view"}
{"image": "/content/invoke-training/sample_data/bruce_the_gnome/002.png", "text": "bruce_the_gnome in front of a fridge frontal view"}
{"image": "/content/invoke-training/sample_data/bruce_the_gnome/001.png", "text": "bruce_the_gnome leaning against a soft wall "}
```

and then started the LoRA training with mostly default values:

```
type: SD_LORA
seed: 1
base_output_dir: output/sd_lora_bruce/
report_to: tensorboard
max_train_steps: null
max_train_epochs: 3
save_every_n_epochs: 1
save_every_n_steps: null
validate_every_n_epochs: 1
validate_every_n_steps: null
model: runwayml/stable-diffusion-v1-5
hf_variant: fp16
base_embeddings: {}
lora_checkpoint_format: kohya
train_unet: true
train_text_encoder: true
optimizer:
  optimizer_type: Prodigy
  learning_rate: 1.0
  weight_decay: 0.01
  use_bias_correction: true
  safeguard_warmup: true
text_encoder_learning_rate: null
unet_learning_rate: null
lr_scheduler: constant
lr_warmup_steps: 0
min_snr_gamma: 5.0
lora_rank_dim: 4
cache_text_encoder_outputs: false
cache_vae_outputs: false
enable_cpu_offload_during_validation: false
gradient_accumulation_steps: 1
mixed_precision: fp16
xformers: false
gradient_checkpointing: true
max_checkpoints: 100
prediction_type: null
max_grad_norm: null
validation_prompts:
- bruce_the_gnome as a cute yoda.
- bruce_the_gnome in a garden.
num_validation_images_per_prompt: 3
train_batch_size: 4
data_loader:
  type: IMAGE_CAPTION_SD_DATA_LOADER
  dataset:
    type: IMAGE_CAPTION_JSONL_DATASET
    jsonl_path: /content/invoke-training/test-dataset.jsonl
    image_column: image
    caption_column: text
  aspect_ratio_buckets: null
  resolution: 512
  center_crop: true
  random_flip: false
  caption_prefix: null
  dataloader_num_workers: 4
```

However the validation images do not seem to change at all during the 3 steps that are configured as default.

Step 1:
<img width="375" alt="bruce_step1" src="https://github.com/invoke-ai/invoke-training/assets/30108765/12017cfe-8ade-4f01-acfc-9e247378024f">

Step 3:
<img width="382" alt="bruce_step3" src="https://github.com/invoke-ai/invoke-training/assets/30108765/c52318d1-a5b0-4ab8-9bc0-8835fd7078ab">

Can someone maybe give me some pointers? Is the dataset just too small/ epoch count too low? Or am I missing something?

**Comment by RyanJDick** [comment]
Thanks for raising this. I'll work on replacing `lambdalabs/pokemon-blip-captions` with something new.

From a quick look at your config, the number of steps is what jumps out. These configs were set for the pokemon dataset, which had ~800 images:
```yaml
max_train_steps: null
max_train_epochs: 3
save_every_n_epochs: 1
save_every_n_steps: null
validate_every_n_epochs: 1
validate_every_n_steps: null
```

For the gnome dataset, with 4 images, I'd recommend something like this:
```yaml
max_train_steps: 2000
max_train_epochs: null
save_every_n_epochs: null
save_every_n_steps: 200
validate_every_n_epochs: null
validate_every_n_steps: 200
```

TBD how well this will actually work. 4 images is less than recommended for LoRA training, so might not be great. Hopefully it works well enough to give you an idea of how it works though.
